config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :dances
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dance.rb
class Dance < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :genre

  validates :title, :introduce, :price, :reservation_time, :genre, presence: true

  validates :genre_id, numericality: { other_than: 1 }
  validates :price, numericality: { greater_than_or_equal_to: 300, less_than_or_equal_to: 9_999_999, message: 'is out of setting range' }, format: { with: /\A[0-9]+\z/, message: 'is invalid. Input half-width characters.' }
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'Hiphop' },
    { id: 3, name: 'Jazz' },
    { id: 4, name: 'Lockin' },
    { id: 5, name: 'Breakin' },
    { id: 6, name: 'Poppin' },
    { id: 7, name: 'House' },
    { id: 8, name: 'Kids' },
    { id: 9, name: 'Tap' },
    { id: 10, name: 'K-POP' },
    { id: 11, name: 'その他' }
  ]
  end

app/models/user.rb
class User < ApplicationRecord
  has_many :dances
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, :email, :profile, :first_name, :last_name, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :first_name, :last_name, :email, :password, :profile])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end
end

app/controllers/dances_controller.rb
class DancesController < ApplicationController
  before_action :set_dance, only: [:show, :edit, :update, :destroy]

  def index
    @dances = Dance.all.order("created_at DESC")
  end

  def new
    @dance = Dance.new
  end

  def create
    @dance = Dance.new(dance_params)
    if @dance.save
      redirect_to dances_path
    else
      render 'new'
    end
  end

    def show
    end

    def edit
    end

    def update
      if @dance.update(dance_params)
        redirect_to dance_path(@dance.id)
      else
        render 'edit'
      end
    end

    def destroy
      if @dance.destroy
        redirect_to dances_path
      end
    end

    private

  def dance_params
    params.require(:dance).permit(:title, :price, :genre_id, :image, :introduce, :reservation_time).merge(user: current_user)
  end

  def set_dance
    @dance = Dance.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dances_helper.rb
module DancesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dances/_form.html.erb
 <div class="img-upload">
      <div class="dance-weight-bold-text">
        ○○○画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"dance-image" %>
      </div>
    </div>
   
    <div class="new-dance">
      <div class="dance-weight-bold-text">
        ○○○名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :title, class:"dances-text", id:"dance-name", placeholder:"○○○（必須 40文字まで)", maxlength:"40" %>
      <div class="dances-explain">
        <div class="dance-weight-bold-text">
          ○○○の説明
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :introduce, class:"dances-text", id:"dance-info", placeholder:"○○○の説明" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>
   
    <div class="dances-detail">
      <div class="dance-select-genre">
        <div class="dance-weight-bold-text">
          ジャンル
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"dance-genre"}) %>
      </div>
      <div class="reservation-detail">
        <div class="dance-weight-bold-text">
          予約時間
          <span class="indispensable">必須</span>
        </div>
        <%= f.datetime_local_field :reservation_time, class:"time-input", id:"dance-time" %>
      </div>
    </div>

    <div class="sell-price">
      <div class="dance-weight-bold-text question-text">
        <span>価格<br>(¥300〜9,999,999)</span>
        <a class="question" href="#">?</a>
      </div>
      <div>
        <div class="price-content">
          <div class="price-text">
            <span>価格</span>
            <span class="indispensable">必須</span>
          </div>
          <span class="sell-yen">¥</span>
          <%= f.text_field :price, class:"price-input", id:"dance-price", placeholder:"例）300" %>
        </div>
        <div class="price-content">
          <span>販売手数料 (10%)</span>
          <span>
            <span id='add-tax-price'></span>円
          </span>
        </div>
        <div class="price-content">
          <span>販売利益</span>
          <span>
            <span id='profit'></span>円
        </div>
        </span>
      </div>
    </div>

app/views/dances/edit.html.erb
<%= render "devise/shared/header" %>
<div class="dances-sell-contents">
  <div class="dances-sell-main">
    <h2 class="dances-sell-title">エントリーの情報を入力</h2>
    <%= form_with model: @dance, url: dance_path(@dance.id), local: true do |f| %>

     <%= render "devise/shared/error_messages", resource: f.object %>
     
    <%= render partial: "form", locals: { f: f} %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <%= render "devise/shared/footer" %>
</div>

app/views/dances/index.html.erb
<div class="dance-container">
  <%= render "devise/shared/header" %>
  <body>
    <div class="dance-main"> 
      <div class="dance-main-image">
        <img src="assets/dance.jpeg" alt="danceimage" width= 100%>
      </div>
    </div>

    <div class='dance-contents'>
      <h2 class='title'>ピックアップジャンル</h2>
      <ul class='dance-lists'>

        <% @dances.each do |dance| %>
          <li class='list'>
            <%= link_to dance_path(dance.id)  do %>
            
              <div class='dance-img-content'>
                <%= image_tag dance.image, class: "dance-img" if dance.image.attached? %>
              </div>

              <div class='dance-info'>
                <h3 class='dance-name'>
                  <%= dance.title %>
                </h3>
                <div class='dance-price'>
                  <span><%= dance.price %>円<br>(税込み)</span>
                </div>
              </div>
            <% end%>
          </li>
        <% end %>
      </ul>
    </div>

    <div class='purchase-btn'>
      <%= link_to new_dance_path do %>
      <span class= "purchase-btn-text">エントリーする</span>
        <%= image_tag 'dancer.jpeg' , size: '185x50' ,class: "purchase-btn-icon" %>
      <% end %>
    </div>
    <footer>
      <%= render "devise/shared/footer" %>
    </footer>
  </body>
</div>

app/views/dances/new.html.erb
<%= render "devise/shared/header" %>
<div class="dances-sell-contents">
  <div class="dances-sell-main">
    <h2 class="dances-sell-title">エントリー</h2>
    <%= form_with model: @dance, url: dances_path, local: true do |f| %>
      <%= render "devise/shared/error_messages", resource: f.object %>

   <%= render partial: "form", locals: { f: f} %>
    
    <div class="sell-btn-contents">
      <%= f.submit "出品する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>

  </div>
  <% end %>
</div>
<%= render "devise/shared/footer" %>

app/views/dances/show.html.erb
<%= render "devise/shared/header" %>

<div class="dance-show">
  <div class="dance-box">
    <h2 class="name">
      <%= @dance.title %>
    </h2>
    <div class='dance-img-content'>
      <%= image_tag @dance.image, class:"dance-box-img" %>
      
    </div>
    <div class="dance-price-box">
      <span class="dance-price">
        ¥ <%= @dance.price %>
      </span>
      <span class="dance-postage">
        (税込) 送料込み
      </span>
    </div>
    
    <% if user_signed_in? && current_user.id == @dance.user_id %>
    <%= link_to '商品の編集', edit_dance_path(@dance.id), method: :get, class: "dance-edit-btn" %>
    <p class='or-text'>or</p>
    <%= link_to '削除', dance_path(@dance.id), method: :delete, class:'dance-destroy' %>
    <%# <% else %> %>
    <%# <% if @dance.order == nil %> %>
    <%# <%= link_to '購入画面に進む', item_orders_path(@dance.id) ,class:"item-red-btn"%> %>
    <%# <% end %> %>
    <% end %>

    <div class="dance-explain-box">
      <span><%= @dance.introduce %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-dance">エントリー者</th>
          <td class="detail-value"><%= @dance.user.name %></td>
        </tr>
        <tr>
          <th class="detail-dance">カテゴリー</th>
          <td class="detail-value"><%= @dance.genre.name %></td>
        </tr>
        <tr>
          <th class="detail-dance">開始時間</th>
          <td class="detail-value"><%= @dance.reservation_time.strftime('%Y/%m/%d %H:%M') %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="comment-box">
    <form>
      <textarea class="comment-text"></textarea>
      <p class="comment-warn">
        ○○○○○○○○○○○○○
        <br>
        ○○○○○○○○○○○○○
      </p>
      <button type="submit" class="comment-btn">
        <span>コメントする<span>
      </button>
    </form>
  </div>
  <div class="links">
    <a href="#" class="change-dance-btn">
      ＜ 前のエントリー
    </a>
    <a href="#" class="change-dance-btn">
      後ろのエントリー ＞
    </a>
  </div>
  <a href="#" class='another-dance'><%= "他のエントリー" %>をもっと見る</a>
</div>

<%= render "devise/shared/footer" %>

app/views/home/index.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <meta charset="UTF-8">
     <link rel="stylesheet" href="assets/style.css">
  </head>
  <div class="container">
    <%= render "devise/shared/header" %>
    <body>
      <div class="main"> 
        <div class="main-image">
          <img src="assets/culture.png" alt="homeimage" width= 100%>
        </div>
      </div>
      <footer>
      <%= render "devise/shared/footer" %>
    </footer>
    </body>
  </div>
</html>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CultureMarket</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>